### ISSUE TITLE
Add code snippets for front matter

### ISSUE THREAD

**Issue by Yajo** [budparr/language-hugo-vscode#13]
I guess being able to inject YAML/TOML front matter would be great.

At least I have this useful snippet in my blog:

```json
{
  "date": {
    "prefix": "date",
    "body": "$CURRENT_YEAR-$CURRENT_MONTH-${CURRENT_DATE}T$CURRENT_HOUR:$CURRENT_MINUTE:$CURRENT_SECOND",
  }
}
```

it helps a lot! I guess there could be more, like a full one with page title, slug, date, tags, draft true/false, etc...

**Comment by budparr** [comment]
Hey, @Yajo This is handled already by Hugo archetypes, which can be easily customized for the need.

**Comment by Yajo** [comment]
Yes, but if I start making a post and then days later I want to update its date to publish it, archetypes don't work for that, and updating the date in this format by hand is a little bit costly, while with the snippet is pretty fast.

**Comment by Yajo** [comment]
OTOH for the default front matter it works great, thanks for the tip!

**Comment by Yajo** [comment]
Ehmm so you aren't going to add the snippet? Want me to do the PR? :roll_eyes:

**Comment by budparr** [comment]
Yes, you're totally welcome to submit a PR
