### ISSUE TITLE
Unable to install, no available version compatible with VS Code '1.22.2`

### ISSUE THREAD

**Issue by rdwatters** [budparr/language-hugo-vscode#2]
Hi there, @budparr. Trying something crazy by switching to VSCode after years of ST3, but I'm getting the following error when trying to install:

```
Unable to install 'budparr.language-hugo-vscode'; there is no available version compatible with VS Code '1.22.2'.
```

Thanks!

**Comment by budparr** [comment]
Hey @rdwatters Have you tried installing it with an updated version of VSCode? It's at `1.25.1` right now, and that's the version I made it with, so perhaps it assumes that's the min.

**Comment by rdwatters** [comment]
You're absolutely right. Closing issue. And thanks for making this awesome plugin. Looking forward to using it on my next project!
